version: "3.7"

services:
  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      USERNAME: root
  rabbitmq:
    image: rabbitmq:3.8.20
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=ecto://root:@db/qiibee_prod
        - SECRET_KEY_BASE=v1ZKC3ehYXOQNgtR34lMD9qw+Rg8UGs0CwiiuGuCwu9NF39awyswRiiVuCxW927J
        - MIX_ENV=prod
    image: app:latest
    environment:
      DATABASE_URL: ecto://root:@db/qiibee_prod
      SECRET_KEY_BASE: v1ZKC3ehYXOQNgtR34lMD9qw+Rg8UGs0CwiiuGuCwu9NF39awyswRiiVuCxW927J
      HOSTNAME: api.sherief.dev
      POOL_SIZE: 20
    restart: on-failure
    depends_on:
      - db
      - rabbitmq
    ports:
      - "4000:4000"
    entrypoint:
      - "./entrypoint.sh"
      - "mysql:3306"
      - "-t"
      - "2"
      - "--"
      - "./run_app.sh"

volumes:
  rabbitmq-data: {}